
language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    
before_install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source

before_script:
  - composer install -n

script:
  - bin/phpspec run -fpretty --verbose
  - bin/phpunit

env:
  - SYMFONY_VERSION=^2.7
