
language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source fi

before_script:
  - composer install -n

script:
  - bin/phpspec run -fpretty --verbose
  - bin/phpunit

env:
  - COMPOSER_PROCESS_TIMEOUT=1800
