
language: php

php:
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7
    
before_install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source

before_script:
  - composer install -n

script:
  - vendor/bin/phpspec run --config=phpspec.yml --no-interaction

env:
  - SYMFONY_VERSION=^2.7
